// src/app/+create-poll/create-poll.component.ts
import { Component, OnInit } from '@angular/core'
import { Router } from '@angular/router'

import { PollService } from '../shared'
import { Poll } from '../shared'

@Component({
  moduleId: module.id,
  selector: 'app-create-poll',
  templateUrl: 'create-poll.component.html',
  styleUrls: ['create-poll.component.css']
})
export class CreatePollComponent implements OnInit {
  poll: Poll
  pollOptionString: string
  constructor(private pollService: PollService, private router: Router) {
  }
  ngOnInit() {
    this.poll = new Poll()
    this.poll.question = ''
    this.poll.options = []
    this.pollOptionString = ''
  }

  createPoll(): any {
    event.preventDefault()
    if (this.poll.question.trim() === '') {
      return alert('Enter Question')
    }
    if (this.pollOptionString.trim() === '') {
      return alert('Enter Poll Options')
    }

    // console.log(`Question : ${this.poll.questione}`)
    // console.log(`Options : ${pollOptionString.split('\n').join(', ')}`)

    // removing null lines if any 
    let optionsArray = this.pollOptionString.trim().split('\n').map(option => {
      let text = option.trim()
      if (text !== '') {
        return text
      }
    })

    if (optionsArray.length && optionsArray.length < 2) {
      return alert('Enter 2 or more options')
    }
    //console.log(optionsArray)

    this.poll.question.trim()     // strip spaces if any?
    this.poll.options = optionsArray
    // console.log('Poll ', this.poll)
    // fire up the poll service
    this.pollService
      .createPoll(this.poll)
      .subscribe(
        (res) => {
          this.poll.question = ''
          this.poll.options = []
          this.pollOptionString = ''
          
          // redirect to create poll via createdPollId
          let { createdPollId } = res;
          let link = ['/poll-info/', {id: createdPollId}]
          this.router.navigate(link)      
         },
        (err) => console.log('Error occured ', err),
        () => console.log('Complete!')
      )
  }
}

<div class="panel panel-default col-sm-6 col-sm-offset-3">
  <div class="panel-body">
    <h2 class="text-center">Create Poll</h2>
    <form>
      <div class="form-group">
        <label>Question:</label>
        <input [(ngModel)]="poll.question" placeholder="Enter a question..." class="form-control">
        <br />
      </div>
      <div class="form-group" >
        <label>Options separate by line-breaks</label>
        <textarea [(ngModel)]="pollOptionString" class="form-control" placeholder="{{ 'Enter\noptions\nlike this'}}" rows="5"></textarea>
      </div>
      <div class="row">
        <div class="col-sm-4 col-sm-offset-4">
          <button class="btn btn-block btn-primary center-block" (click)="createPoll()" >Create</button>
        </div>
      </div>
    </form>
  </div>
</div>

// client/modules/poll/CreatePoll.jsx
import React from 'react'
import $ from 'jquery'
import { browserHistory } from 'react-router'
class CreatePoll extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      optionsCount: 2
    }
  }
  render () {
    const options = this.createOptions.bind(this)()

    return (
      <div className='container'>
        <div className='row'>
          <div className='panel panel-default col-sm-6 col-sm-offset-3'>
            <div className='panel-body'>
              <h2 className='text-center'>Create Poll</h2>
              <form onSubmit={this.createPoll.bind(this)}>
                <div className='form-group'>
                  <label>Question:</label>
                  <input placeholder='Enter a question...' className='form-control' ref='question' /> <br />
                </div>
                {options}
                <div className='row'>
                  <div className='col-sm-4 col-sm-offset-4'>
                    <button className='btn btn-block btn-primary center-block' type='submit'>Create</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    )
  }

  createOptions () {
    const { optionsCount } = this.state
    let options = []

    for (var i = 0; i < optionsCount; i++) {
      const index = i + 1
      let addOption
      let removeOption

      if (i === optionsCount - 1) {
        addOption = this.addOption.bind(this)
      }
      if (i === optionsCount - 2) {
        removeOption = this.removeOption.bind(this)
      }

      const optionElement = (
        <div key={index} className='form-group'>
          <label>Options {index}</label>
          <input
            className='form-control'
            placeholder={`Enter option ${index}...`}
            ref={`option${index}`}
            onFocus={addOption}
            onBlur={removeOption}
          />
        </div>
      )
      options.push(optionElement)
    }
    return options
  }

  addOption () {
    const { optionsCount } = this.state
    this.setState({optionsCount: optionsCount + 1})
  }

  removeOption () {
    const { optionsCount } = this.state
    const lastOption = this.refs[`option${optionsCount - 1}`]
    if (!lastOption.value && optionsCount > 2) {
      this.setState({optionsCount: optionsCount - 1})
    }
  }

  createPoll (event) {
    event.preventDefault()

    const { question } = this.refs

    let data = {
      question: question.value.trim(),
      options: []
    }

    for (let option in this.refs) {
      let optionValue = this.refs[option].value.trim()
      if (option !== 'question' && optionValue) {
        data.options.push(optionValue)
      }
    }

    const checkValidPoll = this.validatePoll(data)
    if (checkValidPoll) {
      return alert(checkValidPoll)
    }

    $.ajax({
      method: 'POST',
      url: '/api/poll',
      data: JSON.stringify(data),
      dataType: 'json',
      contentType: 'application/json'
    }).done((result) => {
      browserHistory.push(`/v/${result.createdPollId}`)
    }).fail((er) => {
      console.log(er)
    })
  }

  validatePoll (pollData) {
    if (pollData.question.length <= 8) {
      return 'Question must be longer than 8 characters.'
    }
    if (pollData.options.length < 2) {
      return 'Must enter atleast 2 options.'
    }
    if (pollData.options.length > 16) {
      return 'Cannot enter more than 16 options'
    }
  }
}

module.exports = CreatePoll
